//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopThoiTrang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuTra()
        {
            this.ChiTietPhieuTras = new HashSet<ChiTietPhieuTra>();
        }
    
        public int IDPhieuTra { get; set; }
        public int IDHoaDon { get; set; }
        public double TongTien { get; set; }
        public int IDNhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuTra> ChiTietPhieuTras { get; set; }
        public virtual PhieuTra PhieuTra1 { get; set; }
        public virtual PhieuTra PhieuTra2 { get; set; }
    }
}
