//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopThoiTrang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VaiTro()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int IDVaiTro { get; set; }
        public string TenVaiTro { get; set; }
        public string MoTa { get; set; }
        public bool QLKhachHang { get; set; }
        public bool QLNhaCungCap { get; set; }
        public bool QLSanPham { get; set; }
        public bool QLHoaDon { get; set; }
        public bool QLNhanVien { get; set; }
        public bool QLLoaiKhachHang { get; set; }
        public bool LapHoaDon { get; set; }
        public bool LapPhieuTraHang { get; set; }
        public bool LapPhieuNhapHang { get; set; }
        public bool QLLoaiSanPham { get; set; }
        public bool BaoCao { get; set; }
        public bool QLSizeMau { get; set; }
        public bool QLVaiTro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
